### ISSUE TITLE
Suggestion: Value splinters as percentage of whole thing

### ISSUE THREAD

**Issue by dobrowolsk** [briansd9/exile-diary#103]
Example: I just found 8 Templar splinters in a map. Exile Diary values them as 3.2 chaos. The templar emblem as a whole just costs 22c on poe.ninja though. So the actual value should be 8% of 22c which is 1.76c.

The same is true for Breach splinters.

The current behaviour over-values splinter drops drastically. So an option to value splinters according to the price of the whole object would be nice.

**Comment by briansd9** [comment]
Hmm, I think setting the "proper" value of items is beyond the scope of this program.

I would prefer to outsource this entirely to poe.ninja, as it's a lot of manual work.

**Comment by dobrowolsk** [comment]
It's just for splinters though. Currently you take the value of a splinter from poe.ninja and use that. Why not replace that with one percent of the value of the respective emblem or breachstone? It's an exception, but a very limited one.

I'm currently farming Legin in Lex Ejoris and the large amount of dropped splinters really distort the profit/map number. I'd really really love this feature. Please? For one of your patreons?

**Comment by briansd9** [comment]
Well, when you put it that way... :-)

It'll take a while though, like I mentioned it's a lot of manual work.

Also, this will apply to everything that splinters (emblem, breachstone, simulacrum, maven's writ, ritual vessel)

**Comment by briansd9** [comment]
This is implemented in v0.2.88, please check if it is as you expect.

Still thinking about how to include this in the settings without having too much clutter, so it can't be turned on from within the app yet. To enable, please edit your `%appdata%\exile-diary\settings.json` and add `"alternateSplinterPricing":true`

**Comment by briansd9** [comment]
Yes, it was a bug, sorry about that... hotfix in new version v0.2.89

**Comment by dobrowolsk** [comment]
Thank you very much for the quick response and fix! I love the new feature!
