### ISSUE TITLE
Net Worth not displaying after upgrade from 2.77 to 2.89

### ISSUE THREAD

**Issue by Bullseye68** [briansd9/exile-diary#109]
Good day,

Just trying to sort this out and was hoping for some assistance.  Seems my Net Worth is not displaying anything any more since upgrading.  Log file shows an error:

2021-02-15 09:43:56.865 [info] stash.html           > TypeError: Cannot read property 'prev' of undefined
    at loadNavLinks (file:///D:/PoEApps/Exile%20Diary/resources/app.asar/stash.html:565:14)
    at loadStash (file:///D:/PoEApps/Exile%20Diary/resources/app.asar/stash.html:332:9)

Is a re-install needed?

Regards,

Mike.

**Comment by briansd9** [comment]
No reinstall needed, we'll get this fixed.

Can you upload the full log file here? Will take a look.

**Comment by Bullseye68** [comment]
Hi Brian,

Thank you for responding.  Yes, here it is...

[log.zip](https://github.com/briansd9/exile-diary/files/5993111/log.zip)

Regards,

Mike.

**Comment by briansd9** [comment]
Got it, thanks!

There was a database update in v0.2.78... just missed it, but we can still do this manually:

1) Go to `Settings -> Debug`
2) Press `Ctrl+Shift+1` to open a developer window
3) Click the `Console` section in the developer window if it's not already showing
4) Type `migrateAll();` at the prompt and press Enter
![Capture](https://user-images.githubusercontent.com/10414098/108157188-17aaec80-711d-11eb-8e9e-b033aca7f9c6.JPG)
5) A bunch of log text should start appearing both in the console and in the `Debug output will be displayed here` text area
6) Wait until the migration is finished (`Done.` should appear in the text area)
7) Your previous stashes should be showing up in the Net Worth screen, and updates will be retrieved again
8) If it doesn't work, or anything in the log looks like an error, send it to me

**Comment by Bullseye68** [comment]
Hi Brian,

Looks like it went through ok... there were some errors at the end... here they are:

﻿
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.059 [info] config.html          > Error executing statement: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: fullrates.date
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.059 [info] config.html          > Error inserting rates for 20200616
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.060 [info] config.html          > Error executing statement: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: fullrates.date
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.060 [info] config.html          > Error inserting rates for 20200701
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.067 [info] config.html          > Inserted rates for 20200702
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.073 [info] config.html          > Inserted rates for 20200704
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.079 [info] config.html          > Inserted rates for 20200707
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.086 [info] config.html          > Inserted rates for 20200714
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.093 [info] config.html          > Inserted rates for 20200720
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.099 [info] config.html          > Inserted rates for 20200725
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.105 [info] config.html          > Inserted rates for 20200811
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.110 [info] config.html          > Inserted rates for 20200812
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.127 [info] config.html          > Inserted rates for 20200919
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.134 [info] config.html          > Inserted rates for 20200921
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.140 [info] config.html          > Inserted rates for 20201004
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.146 [info] config.html          > Inserted rates for 20201101
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.147 [info] config.html          > Error executing statement: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: fullrates.date
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.147 [info] config.html          > Error inserting rates for 20210214
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.148 [info] config.html          > Error executing statement: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: characters.name
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.148 [info] config.html          > Error inserting charName 
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.148 [info] config.html          > Ended migration
D:\PoEApps\Exile Dia…ports\console.js:80 2021-02-16 23:03:34.358 [info] config.html          > Done updating database

Net Worth is showing up and updated!  Thanks!

Regards,

Mike.

**Comment by briansd9** [comment]
Good to hear that, enjoy!

**Comment by Bullseye68** [comment]
Thanks again for your assistance and getting me back up and running.  I really appreciate it and I enjoy the application as part of my PoE experience.  Great work!

Regards,

Mike.
