### ISSUE TITLE
Screenshots ain't saved in desired folder

### ISSUE THREAD

**Issue by AngryRoleplayer** [briansd9/exile-diary#11]
Pressing f8 and nothing. But saves to default game folder

**Comment by briansd9** [comment]
If I understand correctly, you are pressing F8 in-game and the screenshots are being saved properly, but the mods, IIQ and packsize are not being processed?

Can you send me the log file at `%appdata%/exile-diary/log.txt`?

**Comment by AngryRoleplayer** [comment]
Looks like i figured out what was the problem. I actrually needed to select a game folder with screenshots and not just some random folder
![image](https://user-images.githubusercontent.com/22470478/60500196-9215c700-9cc2-11e9-9f59-c5326bc814e1.png)
Why there are two folders here btw?

**Comment by briansd9** [comment]
All working now? That's good.

The "Exile Diary" folder is created by the installer and can be safely deleted.
