### ISSUE TITLE
Stash not updating?

### ISSUE THREAD

**Issue by NitriusX** [briansd9/exile-diary#119]
My stash seems to not have updated since 20210425, though net worth seems to change. Is this a bug or have I missed some settings?

There is items in my stash still showing even though they are no longer there ingame, and I've checked the drop down meny for newer stash, but there is non.

**Comment by NitriusX** [comment]
I forgot that the stash updates after x amount of maps, I thought it was time based, my fault, hehe.

**Comment by briansd9** [comment]
Good to hear it's sorted now - you can make it time-based if you prefer though (`Settings -> Stash -> Retrieve full stash contents every ___`)
