### ISSUE TITLE
Save window size and position between sessions

### ISSUE THREAD

**Issue by aggixx** [briansd9/exile-diary#12]
The program always starts maximized on my main monitor, which is not how I want to use it, so I have to move and resize it every time I start it. It would be great if it saved that automatically.

**Comment by briansd9** [comment]
That's a good idea, I'll implement this for the next build.

**Comment by aggixx** [comment]
Awesome, thanks.

**Comment by jdev21** [comment]
This would be very useful.

**Comment by briansd9** [comment]
Now fixed in v0.2.27.
