### ISSUE TITLE
remove/delete map entry

### ISSUE THREAD

**Issue by hiddenyak** [briansd9/exile-diary#120]
hi, i know this was asked for before 2 years ago, im not sure any other way to bring it up again. Is there any way to remove an unwanted map entry? Even if i have to edit a file its fine, its just messing up my data.

**Comment by briansd9** [comment]
There's a delete button in the lower right corner of the map summary screen... should move it somewhere more visible

**Comment by hiddenyak** [comment]
thanks so much!!!!! i love this tool
