### ISSUE TITLE
Confusion between Laboratory map and Laboratory contract

### ISSUE THREAD

**Issue by worldendDominator** [briansd9/exile-diary#128]
"Laboratory" can be a map name and a contract name. List of areas always counts it as a map, displays Atlas region, and those heists don't count towards "Stats by Area / Heist" in Stats tab (I have all 8 other contract types there but no Laboratory).

I think they should be possible to discern by rogue small talk.

**Comment by briansd9** [comment]
Hmm, to fix this, I would have to play Heist again, which I refuse to do.

Please do not expect that this will ever be fixed.

**Comment by worldendDominator** [comment]
Shouldn't this be as easy as "if any rogue lines are present, count as a contract"?

**Comment by briansd9** [comment]
Yes, should be. Pull requests are welcome if you'd like to have a go at it yourself - relevant code is in this commit: https://github.com/briansd9/exile-diary/commit/3a9acbf077b378edc75db72fab47739de3349dcf
