### ISSUE TITLE
Timer in Azurite Mine doesn't stop when you exit

### ISSUE THREAD

**Issue by worldendDominator** [briansd9/exile-diary#129]
If I log out after delving, the timer keeps counting until I log in again. Generally, the timer here counts all time until you enter a map or other area or end it manually, even if it is days later.
I think the mine should use the same logic as maps: if you leave it and enter another (non-town, non-hideout) area afterwards, only the time until you left it counts.

**Comment by worldendDominator** [comment]
On a second thought, there's a blurry case where you delve, exit, return another day, and delve again. The only difference from "delve, hideout, delve again" or "delve, crash, relog, delve again" is the amount of time between leaving and returning.

But at least for "delve, exit, return, enter map" it should be an obvious fix.

**Comment by briansd9** [comment]
Hmm, how would you propose to set the endpoint of the delve run then? Nothing is logged in Client.txt when exiting the game (either by Alt-F4, or crashing out).

**Comment by worldendDominator** [comment]
Ah, I didn't realize that. Looks like there's nothing to do if you just leave.
However, entering a non-delve area should still be an end point if you don't reenter the mine afterwards. So if you ho to HO after you finish delving, it will count as you stopping there.

**Comment by briansd9** [comment]
>  So if you go to HO after you finish delving, it will count as you stopping there

I think this is the current behavior... it doesn't do this for you? Will review the code.

**Comment by worldendDominator** [comment]
Just tested it and yes, it already works like this and I didn't realize it.
