### ISSUE TITLE
Does this tracker read memory?

### ISSUE THREAD

**Issue by Cloudslapper** [briansd9/exile-diary#134]
Does the tracker read your memory for the data? or is it only using public information?
I'd hate to get my account banned for simply tracking a bunch of currency.

**Comment by briansd9** [comment]
No memory reading involved, only information accessible through legitimate ways is used (`https://pathofexile.com/character-window/get-items?league=Expedition&accountName=YOURNAME&character=YOURCHARNAME` for example, same as Path of Building).

**Comment by Cloudslapper** [comment]
Thanks a lot for the clarification. Much appreciated.
