### ISSUE TITLE
Issue on Windows 11

### ISSUE THREAD

**Issue by Drakkhan** [briansd9/exile-diary#135]
Hello, 

when i start the App first time i wont be able to setup the PoE Client path
When i click on it, it opens the file Explorer Window after i navigate to my PoE Folder and click on client.exe and hit on open nothing happens. The Log.txt seems normal (will be linked) and i can't find a way to get it to work. 

Thanks for this great app besides this Bug

> 2021-08-31 06:00:37.326 [info] main.js              > Starting Exile Diary v0.3.4
> 2021-08-31 06:00:36.497 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:00:37.326 [info] main.js              > Initializing components
> 2021-08-31 06:00:37.888 [info] main.js              > Checking for update
> 2021-08-31 06:00:36.513 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:00:37.341 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:00:37.341 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:00:37.888 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:00:37.888 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:00:38.154 [info] main.js              > Generated new staging user ID: a5bf2729-a5cd-5529-8194-a57e80984397
> 2021-08-31 06:00:38.916 [info] StashGetter.js       > Starting StashGetter instance
> 2021-08-31 06:00:38.916 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:00:38.916 [info] StashGetter.js       > No league set (first run?) - returning
> 2021-08-31 06:00:38.916 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:00:39.325 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\config.html
> 2021-08-31 06:00:39.331 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:00:39.796 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\config.html
> 2021-08-31 06:00:39.796 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:00:39.796 [info] DB.js                > Unable to get league DB
> 2021-08-31 06:00:40.211 [info] main.js              > Update for version 0.3.4 is not available (latest version: 0.3.4, downgrade is disallowed).
> 2021-08-31 06:01:40.941 [info] main.js              > Starting Exile Diary v0.3.4
> 2021-08-31 06:01:40.082 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:01:40.941 [info] main.js              > Initializing components
> 2021-08-31 06:01:41.520 [info] main.js              > Checking for update
> 2021-08-31 06:01:40.082 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:01:40.941 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:01:40.941 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:01:41.520 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:01:41.520 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:01:42.552 [info] StashGetter.js       > Starting StashGetter instance
> 2021-08-31 06:01:42.552 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:01:42.552 [info] StashGetter.js       > No league set (first run?) - returning
> 2021-08-31 06:01:42.552 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:01:42.986 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\config.html
> 2021-08-31 06:01:42.992 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:01:43.469 [info] main.js              > Update for version 0.3.4 is not available (latest version: 0.3.4, downgrade is disallowed).
> 2021-08-31 06:01:43.481 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\config.html
> 2021-08-31 06:01:43.481 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:01:43.482 [info] DB.js                > Unable to get league DB
> 2021-08-31 06:06:06.312 [info] main.js              > Starting Exile Diary v0.3.4
> 2021-08-31 06:06:06.126 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:06:06.312 [info] main.js              > Initializing components
> 2021-08-31 06:06:06.426 [info] main.js              > Checking for update
> 2021-08-31 06:06:06.127 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:06:06.314 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:06:06.314 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:06:06.427 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:06:06.427 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:06:07.022 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\config.html
> 2021-08-31 06:06:07.023 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:06:07.347 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\config.html
> 2021-08-31 06:06:07.347 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:06:07.347 [info] DB.js                > Unable to get league DB
> 2021-08-31 06:06:07.438 [info] StashGetter.js       > Starting StashGetter instance
> 2021-08-31 06:06:07.438 [info] settings.js          > Cannot find module 'C:\Users\DJ-Ni\AppData\Roaming\exile-diary\settings.json'
> Require stack:
> - C:\Program Files\Exile Diary\resources\app.asar\modules\settings.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ItemPricer.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\RunParser.js
> - C:\Program Files\Exile Diary\resources\app.asar\modules\ClientTxtWatcher.js
> - C:\Program Files\Exile Diary\resources\app.asar\main.js
> - 
> 2021-08-31 06:06:07.438 [info] StashGetter.js       > No league set (first run?) - returning
> 2021-08-31 06:06:07.438 [info] settings.js          > Unable to load settings.json
> 2021-08-31 06:06:08.723 [info] main.js              > Update for version 0.3.4 is not available (latest version: 0.3.4, downgrade is disallowed).
> 
>

**Comment by briansd9** [comment]
> When i click on it, it opens the file Explorer Window after i navigate to my PoE Folder and click on client.exe

That's the wrong file... look for `Client.txt` instead, it should be located in the `logs` folder inside your PoE install location.

Thanks for the report though - will add an error message if an invalid file is selected (currently it just does nothing, as you observed). Sorry for the inconvenience

**Comment by Drakkhan** [comment]
ok im a idiot, thanks works like a charm xD
