### ISSUE TITLE
v0.3.4 - "Errors found while parsing filter" Latest (Scourge) NeverSink filter not working

### ISSUE THREAD

**Issue by DevConFox** [briansd9/exile-diary#139]
Tried loading the updated FilterBlade files for the 3.16 Scourge league, but every file I load could not be parsed.
Initially, I tried the NeverSink SC Economy filters, only customized with the Azurite Style. None of the seven files could be parsed.
Trialed and errored with the standard normal style, same result.

Files are attached. _1_Regular is the Azurite Style one.
[ParsingError.zip](https://github.com/briansd9/exile-diary/files/7404504/ParsingError.zip)

**Comment by worldendDominator** [comment]
Same here. I also have examples of filters that work (older one, from previous league) and that doesn't (from this league).

[works.txt](https://github.com/briansd9/exile-diary/files/7536604/works.txt)
[worksnt.txt](https://github.com/briansd9/exile-diary/files/7536605/worksnt.txt)

Edit: unmodified filter doesn't work either.

Edit2: it's base defense percentile that's causing this.

**Comment by DevConFox** [comment]
Tidying up old issues that no longer seem relevant.
