### ISSUE TITLE
Screenshots + ReShade

### ISSUE THREAD

**Issue by Alcohealix** [briansd9/exile-diary#16]
I've noticed I'm unable to use the screenshot feature when using the post-processing injector, ReShade. Switching to another installation without ReShade and it works fine. Would it at all be possible to have these two work alongside each other?

Thanks for all your work, this app is great.

**Comment by briansd9** [comment]
The screenshot feature is very dependent on the standard graphical appearance of PoE... as ReShade allows it to be customized to an unlimited extent, I see no way to implement your request right now. Very sorry about that
