### ISSUE TITLE
Deaths being incorrectly reported when in a party

### ISSUE THREAD

**Issue by 99TonyStark99** [briansd9/exile-diary#23]
My son and I are partying together, we are in the same guild (not sure if this is a cause but...)
'
Anyhow, when his toon dies, it counts as a death in the log for me on that map.

**Comment by briansd9** [comment]
Good catch, any appearance of "slain" in the log counts for you.

Will be fixed in the next build, thanks!

**Comment by briansd9** [comment]
Fixed in v0.2.30.
