### ISSUE TITLE
Net Worth tab

### ISSUE THREAD

**Issue by Steel-Blade** [briansd9/exile-diary#24]
When I click it, nothing happens, I just see a black screen,
Any idea of what might be the problem?

https://www.dropbox.com/s/d0kx1g0hxmftwqj/screenshot%202019-09-01%2010.38.51.png?dl=0

**Comment by briansd9** [comment]
Hi, have you updated to the latest version (v0.2.31)?

If so, have you set it up properly in the settings screen (stash tabs to watch, how often to check net worth)?

If you've done all that, please send me the log at `%appdata%\exile-diary\log.txt`, I'll get this fixed for you.

**Comment by Steel-Blade** [comment]
I just updated to v0.2.31

I am still seeing just a black screen.
https://www.dropbox.com/s/zamhqb7hfl8n2je/screenshot%202019-09-01%2017.36.43.png?dl=0

here is the log file
https://www.dropbox.com/s/46kybxip5p68qu8/log.rar?dl=0

Regards

**Comment by briansd9** [comment]
Oops sorry, I forgot to mention that you need to do one map after updating, as the stash check can only happen after a processed map run. Sorry about that

If it still doesn't work, can you also upload me your character's data file `%appdata%\exile-diary\<CHARNAME>.db`?

**Comment by stile17** [comment]
I have the same issue with latest version (0.2.34). Text "Item Unit Value" shows for a split second and then exactly the same effect like attached sceenshot by Steel-Blade.

There is nothing suspicious in log file.

**Comment by briansd9** [comment]
Hi @stile17, sorry about that. Was it working properly in the previous version?

Would like to see the log file anyway, could you upload it for me?

**Comment by stile17** [comment]
I run also 0.2.33, same effect.
Log file: https://drive.google.com/open?id=1C3S-tAmM7xscFaVXZCxPPBQSvWeGiURq

**Comment by briansd9** [comment]
Have you set up which tabs to use for getting net worth (Settings -> Stash)?

**Comment by stile17** [comment]
> Have you set up which stash tabs to use for getting net worth (Settings -> Stash)?

Probably this is problem ;) I didn't notice that on page "Settings" is "Stash" tab. When I come back from work I will verify this.

**Comment by stile17** [comment]
I verified. Everythink is working now. For me this issue can be closed. Thank you :)

**Comment by briansd9** [comment]
Got it, thanks!

Will leave this open for now as a reminder that the stash configuration requirement should be made clearer

**Comment by DasAtom** [comment]
Heya, I've got the same problem. However I am not able to find a page in the settings for the stash. Are there any prerequirements for it to appear? [I assume this is the area we are talking about?](https://i.imgur.com/KC7fH1u.png). I am using V0.2.34

**Comment by briansd9** [comment]
Fixed in v0.2.36.
