### ISSUE TITLE
Maps not being tracked at all.

### ISSUE THREAD

**Issue by Ginixx** [briansd9/exile-diary#26]
Don't know if im doing something wrong but all the info i need to fill in has been filled in correctly but no maps are being tracked at all?

tried re entering all the info.
Running as administrator.
But nothing seems to help?

**Comment by briansd9** [comment]
Hi, sorry about that, we'll get this fixed.

Can you upload me your log file at `%appdata%\exile-diary\log.txt`?

**Comment by Ginixx** [comment]
So after posting this it started tracking some maps for me. 
But now it stopped doing that again.
[https://pastebin.com/GiHAuMPL](url)
that is a pastebin link of my logs.

**Comment by briansd9** [comment]
Hi, sorry for delayed reply. Are you still experiencing problems after updating to the latest version?

I've checked your log file, nothing seems obviously wrong. Can you give me more details? How does the program's behavior differ from what you expect?

**Comment by Ginixx** [comment]
Hey, also sorry for the late reply from my end.
It had been working for a couple of days but stopped again.
re entered all the info multiple times.
-Account Name
-POESESSID
-active character
- client.txt location

but nothing seems to work.
i run a couple of maps and my most recent maps tab is still empty.
i have ran the program with administrator rights but also doesn't seem to change anything.
here is my log again: https://pastebin.com/d2pSzVzF
i noticed it states: 

> 2019-09-08 11:15:08.963 [info] settings.js          > Unable to load settings.json

a couple of times

**Comment by briansd9** [comment]
Hmm, looking at today's entries in your log file (2019-09-23, between 12:35 and 14:45), nothing was recorded at all (area changes, items picked up, XP). Were you playing the game during this time?

If so, can you check your `C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt` and see if there are entries for your in-game actions during the same time period? There should be lines such as "You have entered <area name>" whenever you go to a different area.

**Comment by Ginixx** [comment]
After checking the client.txt i noticed nothing i did today is in there.
any idea what i can do to fix that?
i guess that is also the reason exile diary is not able to log anything.

**Comment by briansd9** [comment]
Try deleting Client.txt and then starting the game again.

If it still doesn't work, I'm out of ideas... GGG support should be able to help https://www.pathofexile.com/support

**Comment by Ginixx** [comment]
this has fixed it thanks for the help.
