### ISSUE TITLE
detect character automatic

### ISSUE THREAD

**Issue by kevindevm** [briansd9/exile-diary#29]
if u enter this page 
https://www.pathofexile.com/character-window/get-characters?accountName=[AccountName]
with the cookie u can get the last character active
maybe add and option like "You level too many characters? :P"
and call this every few second
also could u add a opction to start with windows? and maybe minimize to tray? 

again thanks for this amazing app ♥

**Comment by briansd9** [comment]
You mean checking the character list every x seconds to automatically switch the tracked character? Not a good idea, the app will get blocked for spamming the API and stop working. Just change character yourself :-)

I think adding as a startup program is a bit too intrusive... minimize to tray is ok though.

**Comment by kevindevm** [comment]
> You mean checking the character list every x seconds to automatically switch the tracked character? Not a good idea, the app will get blocked for spamming the API and stop working. Just change character yourself :-)

then i could write a simple ahk to change the character and then restart the program? if so where do i write the new character?

**Comment by kevindevm** [comment]
thanks

**Comment by kevindevm** [comment]
@briansd9 you get the items with this link ? 
https://www.pathofexile.com/character-window/get-items?accountName=ACCOUNT&character=CHARACTERNAME ??
if so in that page there is a key "lastActive":true, so u dont need to spam to check characters, only check if there is not the key?
anyways that was a a suggestion
