### ISSUE TITLE
Not tracking pickups

### ISSUE THREAD

**Issue by Sephiphor** [briansd9/exile-diary#3]
I've been using this since the start of the Betrayal and it had been working perfecting until tonight.  Its properly tracking the maps that I run, but it has stopped tracking anything that I pick up.  When I select a map after it logs it, it shows all of the data about the map from the screenshot I take but nothing shows in the list for the items.
![screenshot-20181210103047](https://user-images.githubusercontent.com/43625260/49780317-46baad80-fccb-11e8-8c52-3feec40dce6d.png)

**Comment by briansd9** [comment]
Hi, sorry about that, I'll get it fixed. Can you upload the log file `%appdata%/exile-diary/log.txt`?

**Comment by Sephiphor** [comment]
[log.txt](https://github.com/briansd9/exile-diary/files/2670029/log.txt)

**Comment by briansd9** [comment]
Noticed from the log file that your POESESSID seems to be no longer valid. Can you enter it again in the settings screen and see if this fixes the problem?

If not, could you also upload the data file `%appdata%/exile-diary/<CHARNAME>.db`? It's OK to zip it first so you can just drag the zipfile directly into this comment box.

**Comment by Sephiphor** [comment]
The POESESSID was the issue, thank you. It might be a good idea to have something in the tool that can notify if the ID expires/stops working.

**Comment by briansd9** [comment]
Got it, thanks. This will be implemented in the next update.
