### ISSUE TITLE
some error?

### ISSUE THREAD

**Issue by kevindevm** [briansd9/exile-diary#30]
![image](https://user-images.githubusercontent.com/7692819/64954898-38eb1780-d85d-11e9-98b9-8b770a681855.png)

[log here](https://pastebin.com/ZiMzesXp)

**Comment by briansd9** [comment]
It's an instance of the bug you found in #25.

Nothing happened in Aspirants' Plaza so the area was ignored completely (proper behavior would be to log it as an invisible "nothing happened" run) which made it carry over to your next map. Will be fixed in the next build, sorry about that

**Comment by briansd9** [comment]
Fixed in v0.2.36.
