### ISSUE TITLE
Maps tracking unusually; client appears to be logged only after PoE and exile diary program resets

### ISSUE THREAD

**Issue by Biggoron144** [briansd9/exile-diary#31]
I have double checked my settings according to the guide and everything appears to be accurate. Maps are being "logged," but the income from the maps is accumulated together between PoE sessions and the first time I log in (when I enter my hideout, I think) Exile Diary spits out that it's logged a new map "Glimmerwood Hideout"

![image](https://user-images.githubusercontent.com/36545366/64973128-11ea1100-d870-11e9-85bc-33f2a9ad8b67.png)
[log.txt](https://github.com/briansd9/exile-diary/files/3617095/log.txt)
https://pastebin.com/nxbvbCxV also has my log

**Comment by briansd9** [comment]
Glimmerwood hideout was being treated as a map area instead of a hideout, sorry about that. Fixed in v0.2.36.
