### ISSUE TITLE
should not be one each?

### ISSUE THREAD

**Issue by kevindevm** [briansd9/exile-diary#32]
![image](https://user-images.githubusercontent.com/7692819/65276464-293e2e00-dafe-11e9-97c4-109d947733c6.png)

![image](https://user-images.githubusercontent.com/7692819/65276549-57237280-dafe-11e9-8d6e-c99940d00054.png)

**Comment by briansd9** [comment]
Behavior during acts 1-10 not guaranteed to be stable - this is a program for tracking maps after all :-)

Tried this out before and found that 1 entry per area was too much clutter.

**Comment by kevindevm** [comment]
oh ok
