### ISSUE TITLE
updating to v0.2.41 breaks exile diary

### ISSUE THREAD

**Issue by 99TonyStark99** [briansd9/exile-diary#39]
after manually downloading and installing v0.2.41, the program no longer tracks anything, it still shows my previous maps, and net worth.
re-selecting the poe log file etc. has not helped, neither has rebooting the pc, restarting the app etc.

also, It doesn't seem to keeping an error log file anywhere (that I can find anyhow)

**Comment by briansd9** [comment]
Should be fixed in v0.2.42.

The data for map runs done while using v0.2.41 is still there (just not displayed properly), a recovery option for these will be included in a future version.

**Comment by 99TonyStark99** [comment]
can confirm, it's now working properly
