### ISSUE TITLE
Dosn't show anything..

### ISSUE THREAD

**Issue by QCElysiums** [briansd9/exile-diary#4]
Hello there, so like the title said, it show nothing, nothing appear on the program after i done a map..

https://gyazo.com/46b344166f92785d761875c205a96710

I did 3 maps, i did the screenshots before starting killing on every maps.. any help?

**Comment by briansd9** [comment]
Hi, can you upload your log file for me? It's located at `%appdata%/exile-diary/log.txt`

**Comment by QCElysiums** [comment]
[log.txt](https://github.com/briansd9/exile-diary/files/2674855/log.txt)

**Comment by QCElysiums** [comment]
I really want this program to work, help please :D

**Comment by briansd9** [comment]
Hmm, the problem seems to be that changes to your Client.txt aren't being detected.

Can you confirm that `C:\Program Files (x86)\Steam\steamapps\common\Path of Exile\logs\Client.txt` exists on your computer? If you open it, does it contain information about what you've recently done in-game (maps you've entered, etc.)?

**Comment by QCElysiums** [comment]
It doe exist, but apparently nothing after 2018/12/01... lol

**Comment by QCElysiums** [comment]
OH my bad... i forgot, i re-installed it into my D:\ LOL

**Comment by QCElysiums** [comment]
I give you somes news in like 10min

**Comment by QCElysiums** [comment]
And did i've to take the screenshot at all maps im doing? If yes, did i've to wait without moving until the program say he loaded it?

**Comment by briansd9** [comment]
The screenshot is not required, if you don't care about saving information about the map mods you can skip it. (Also, you can start playing as soon as you've taken the screenshot, no need to wait until you get the "Got area info from <mapname>" notification)

Is it working now?

**Comment by QCElysiums** [comment]
Apparently no..

**Comment by QCElysiums** [comment]
[log.txt](https://github.com/briansd9/exile-diary/files/2674989/log.txt)

**Comment by QCElysiums** [comment]
I need to re-open the program for it to work??

**Comment by QCElysiums** [comment]
Oh, it just appear what i just did! XD

**Comment by QCElysiums** [comment]
It's okay then, i was just in need to re-open the program, thanks you for your help!!!!

**Comment by briansd9** [comment]
Awesome! I'll close this issue now.

If there are any other problems, just let me know.
