### ISSUE TITLE
Doesnt register maps

### ISSUE THREAD

**Issue by Armux** [briansd9/exile-diary#41]
Hello,
since last patch it started somewhat to work, but still its not working like it did in blight.. It just sums all my days farming and report it as my hideout farm run.. 
![ed](https://user-images.githubusercontent.com/15680479/71412602-1be19400-2657-11ea-90ac-9ba16315a5b0.jpg)
what is wrong with it?
[log.txt](https://github.com/briansd9/exile-diary/files/3998213/log.txt)

**Comment by briansd9** [comment]
Failed to recognize Celestial Nebula Hideout as a hideout (was treating it as a map area)... very sorry about that. Fixed in v0.2.43, please check

**Comment by Armux** [comment]
Yes, works now. Thanks for the quick fix
