### ISSUE TITLE
Excluding items from registering?

### ISSUE THREAD

**Issue by CubeStick** [briansd9/exile-diary#45]
Hello, I love this program and use it every day to track my maps.
However, I pick up random good rares and normal leather belts.
These are counted in the total and make up for a wrong total Chaos amount collected.
For example in the new league right now a normal leather belt is flagged as 2c, this is not what I would want.

Is there a way to exclude these (or other certain) items from being registered?

**Comment by briansd9** [comment]
Hello, yes, there is an option for this in the Settings screen:

![](https://user-images.githubusercontent.com/10414098/72203282-6874fe00-34a4-11ea-91e9-89fd897ed9fa.JPG)

**Comment by CubeStick** [comment]
Ooh, I see. Gonna try that out for now, thanks!
