### ISSUE TITLE
Is there any way to manually refresh net worth?

### ISSUE THREAD

**Issue by ifbatmanwasreal** [briansd9/exile-diary#46]
I just hate that I have to put another map in to get the stats of my latest map. Was wondering if there was any way I could manually refresh net worth when I get to my hideout. This way I can see what I got right when I'm done.

**Comment by briansd9** [comment]
The PoE servers have rate limits on the number of requests you can make. If the limit is exceeded you get temporarily banned, which causes the entire app to break.

Getting your stash tabs causes a lot of requests to be made. For this reason, I do not intend to implement a manual "update net worth" control.

If you really want to, you can edit the settings file to get net worth every 1 minute, but something will probably go wrong.

**Comment by YakMaster** [comment]
If you are asking how to see the results of a map without running a new map then it is in the documentation. Basically 
1/ Hit tab to show map stats when you enter map. 
2. When finished map, message yourself the word "end". It wont refresh your net worth but it will show you what you picked up that map. 

I only have to do step 1 once, then messaging myself after every map updates the map list. 
For some reason Screen shotting wont list my Level/IIQ IR or pack size, so i just do it once at the start of a session.

I do agree an "Map Complete" button might be a nice QOL (as would the Chaos to Ex rate on the Net worth) but not complaining - the program is awesome as is.

_From the wiki:
Optional: If you want to manually signal Exile Diary to process your map run (when you're done playing for the night, for example), send yourself a whisper message containing only the word "end" when you're back in your hideout. Note: this only works if you have extracted the area info via screenshot, if you are in fully automatic mode the only way to end a map run is to start a new one._
