### ISSUE TITLE
Jeweller's Orb vendor recipe & 6 sockets

### ISSUE THREAD

**Issue by torengen** [briansd9/exile-diary#50]
This is not a bug per say, but I do think that it leads to a somewhat skewed and misleading currency/map rate.

The map tracker seems to report 6-socketed armors by their market value on trade sites(I think?), when the reality is, most players are likely just vendoring them. Very few people are selling 6-socketed conquest chainmails for 3c on trade. This skews profit/map - sometimes a little(3c on a 60c worth of return doesn't matter), but sometimes a lot(15c on a map that only gave 6 socket armors is all the profit).

It seems appropriate for there to be an option to set their value to 7 jeweller's.

**Comment by briansd9** [comment]
There is a configuration option for this: `Settings -> Stash -> "Ignore non-bulk items less than ___ in value"`

Any items under this value which have an applicable vendor recipe (7 jewellers / 1 divine / 1 chrom) will be priced accordingly.

This option will be made clearer in the next release, thanks for the report.
