### ISSUE TITLE
Main Page: Can no longer sort by column

### ISSUE THREAD

**Issue by Tallion99** [briansd9/exile-diary#52]
New map runs are added to the bottom of the of the list on the main page instead of the top.

**Comment by 99TonyStark99** [comment]
Having the same issue here, since the most recent update

**Comment by briansd9** [comment]
Hmm, this was actually a bug fix... the main page would load with the latest map runs at the bottom, but new rows were added to the top. 

Would you prefer that "most recent maps" always have the newest ones at the top instead?

**Comment by 99TonyStark99** [comment]
That'd be perfect for me

**Comment by Tallion99** [comment]
Same here. The issue is if you don't have your screen big enough to see all 10 maps, then you have to scroll down to see the last maps ran. I have mine on a 2nd monitor and it shares space with the trade site so this is how i use the app...Thanks!
![image](https://user-images.githubusercontent.com/53978851/76874408-2918b400-683d-11ea-9701-add17a9fcce1.png)

**Comment by Zarggg** [comment]
> Would you prefer that "most recent maps" always have the newest ones at the top instead?

I would like this behavior as well.

**Comment by briansd9** [comment]
Fixed in v0.2.49.
