### ISSUE TITLE
What does the ItemFilter do actually?

### ISSUE THREAD

**Issue by Rottenbeer** [briansd9/exile-diary#53]
I'm wondering why I should upload a filter and what it does.
I can not find it in the documentation.
Can you please help me?
THanks!

**Comment by briansd9** [comment]
It shows items the way your loot filter would render them:
![2](https://user-images.githubusercontent.com/10414098/76869382-2f417b80-68a3-11ea-9d9c-7788781c876a.JPG)

Here's the default "no filter" appearance for comparison:
![1](https://user-images.githubusercontent.com/10414098/76869379-2d77b800-68a3-11ea-8409-74f236502ac7.JPG)

Thanks very much for asking, will add this to the documentation.

**Comment by Rottenbeer** [comment]
Cool feature!
Thanks for explaining it!

**Comment by Rottenbeer** [comment]
Feel free to close it when you think it can be closed ;)

**Comment by briansd9** [comment]
Added more info to the wiki page. Closing now, thanks.
