### ISSUE TITLE
Exile Diary fails to start

### ISSUE THREAD

**Issue by worldendDominator** [briansd9/exile-diary#55]
When I start the program, all that happens is I get two processes in the task manger that use about 30 and 60 mb of RAM and zero other resources. I have Windows 10 and the most recent release version of Diary (although the same happened on .45 as well).

**Comment by briansd9** [comment]
Hi, sorry about that, we'll get this fixed.

Can you send me the log file at `%appdata%/exile-diary/log.txt`?

**Comment by worldendDominator** [comment]
[log.txt](https://github.com/briansd9/exile-diary/files/4487173/log.txt)

Taking a look at that log file, after a certain point there's a flood of "Unable to load settings.json" and "No settings file found, can't initialize DB".  Settings.json exists in the same folder, but it's empty. Removing the exile-diary folder lets the program launch properly (but without login data, obviously). I think the fix should be treating a blank settings file as no file.

What I think is interesting is that the first "unable to load" message appeared in the middle of a play session. I have no idea why it was blanked.

**Comment by briansd9** [comment]
Hmm, no idea either why your settings.json became empty, I'll have to investigate this some more... but just deleting it should make the program usable for you again (you'll be prompted to set up from scratch, but your data will still be there).

Thanks very much for the report, will fix as you suggested.
