### ISSUE TITLE
Feature Request: To disable price checking of gems being swapped in inventory

### ISSUE THREAD

**Issue by houmanah** [briansd9/exile-diary#58]
Hi Brian,
Love your tool! But there's one small "inconvenience" and would just love to put it out there is about gems when being swapped in and out are being counted as "loot". Is there any workaround in the settings to not take this into account? 

Apart from that everything works beautifully!

**Comment by briansd9** [comment]
Oops, very sorry about that... will fix in the next build.

There are two possible in-game workarounds:
- put the other gem in your weapon swap, if there's still room
- unsocket both gems before starting the map (items already in your inventory won't be counted as loot)

**Comment by houmanah** [comment]
Thanks for the fast reply! So how it is registering the gems atm are:

1. Have "Chain support" socketed into chest.
2. Have "Barrage Support" sitting inside inventory.
3. When I swap Barrage for Chain support during bosses, either the Barrage/Chain will be recognized as loot.

**Comment by briansd9** [comment]
Should be fixed in v0.2.55, please check.
