### ISSUE TITLE
Feature request: disable maps from 'recent map summary' (tab 'Main')

### ISSUE THREAD

**Issue by sandsynligvis** [briansd9/exile-diary#59]
Hello, could you consider disabling (giving us an option would be the best idea) maps from the summary? They are nowhere worth the value thats is being showed, e.g in this run maps shows almost 30% of overall value, which misleads the whole run.
![image](https://user-images.githubusercontent.com/9571695/81152873-a7aee980-8f82-11ea-91f8-fb9abb85107b.png)

**Comment by briansd9** [comment]
Seems like a good idea, I will consider it.

Just to clarify though, the map summary will always display the value of the item at the time you picked it up. You're correct that the maps in this screenshot are nowhere near this price as of right now, but it looks like this was taken somewhat earlier in the league?

**Comment by sandsynligvis** [comment]
It was taken today in standard, which is even worse because maps <t16 has almost zero value.

**Comment by briansd9** [comment]
Ah, understood.

**Comment by briansd9** [comment]
Added in v0.2.57, please check.

**Comment by sandsynligvis** [comment]
You have done everything i wanted, thank you!
