### ISSUE TITLE
Feature request: fixed price

### ISSUE THREAD

**Issue by sandsynligvis** [briansd9/exile-diary#60]
Could you develop an option to put the fixed price for currency? It could be really usefull for lower tiers of oils (clear, sepia etc) - they are unsellable, yet when quantity goes up to thousands - it  misleads their real value.

**Comment by briansd9** [comment]
Sorry, I won't be doing this... I would prefer to leave the work of item pricing entirely to poe.ninja, and consider adding item values manually to be beyond the scope of this application.
