### ISSUE TITLE
Feature Request: Item Tracking Options

### ISSUE THREAD

**Issue by Tallion99** [briansd9/exile-diary#61]
I am wondering if it is possible to get a better handle on the pricing variations by adding in the ability to not track certain items?
Personally i would be interested in an option that stopped all rare items from being tracked. My filter and price checker takes care of those items for me.

Maybe on the setting page have some options like these?
- Don't track rare items.
- Don't track oils.
- Don't track div cards.
- Don't track div cards valued under xx chaos.
- Don't track essences.

Not sure if it is feasible but figured i would throw it out to see what you think. Thanks!

**Comment by sandsynligvis** [comment]
I dont know if that matters, but adding 'valued under xx chaos' would be great for all oils, cards and essences.

**Comment by briansd9** [comment]
Would like to get a bit of clarity before investing more effort in this. When would you pick up an item that's not worth counting as loot? As you said, would this not be better handled by your item filter (i.e. just don't pick them up in the first place)?

**Comment by Tallion99** [comment]
In this case these items are Shaper items and technically could sell for their listed price.
They also account for almost 50% of the map total.
But I either use them for exalt shard recipe or I vendor them. Very few actually go in my for sale tab.
![image](https://user-images.githubusercontent.com/53978851/81421064-7d8e3080-9116-11ea-9394-33fc6b482e87.png)

On the opposite side There are some rares that are valuable and are sold or used.
In this case this shaper shield was worth a lot and sold for close to the listed price.
But in this case my filter gave me the heads up it was very valuable. 
![image](https://user-images.githubusercontent.com/53978851/81421091-87b02f00-9116-11ea-863a-a3172c38b8c3.png)

In this case if we could do a Don't track rare items valued under XX chaos it would work great.
Otherwise if it was a choice between tracking all rares or tracking no rares, I would choose no rares.

I don't want to come off as saying one way it right or wrong, the app is pretty fun to use and adding the ability to further refine the loot would be a pretty cool feature!

**Comment by briansd9** [comment]
Doesn't the "ignore non-bulk items less than __ in value" setting do exactly what you need already?

**Comment by Tallion99** [comment]
Yes, I had the value set too low. It now filters out the rares items.
