### ISSUE TITLE
Add support for Vaal Side areas (from sacrifice fragments)

### ISSUE THREAD

**Issue by btrisler** [briansd9/exile-diary#65]
I'm planning to run a ton of vaal side areas at league start using Sacrifice fragments in the atlas (1 at a time).

It would be great if they could be tracked.  I'm not sure if it's more useful to group them as "Vaal side area" since the map is random, or to track them separately.

**Comment by briansd9** [comment]
Good find, I hadn't thought of this before... ran one just now, it seems to be handled properly. The actual name of the area will be logged as the map name.

If you've already tried it, was anything not working as you expected?

**Comment by btrisler** [comment]
Looks like I can close another one.  My fault, I didn't realize when changing characters I needed to reload.
