### ISSUE TITLE
Minimise to tray

### ISSUE THREAD

**Issue by tonytamps** [briansd9/exile-diary#67]
It would be useful if I could have the application minimise to the system tray along with most other tools that tend to run persistently.

**Comment by briansd9** [comment]
That's a good idea, will try to have this ready for the next update.

**Comment by briansd9** [comment]
Implemented as an option in v0.2.62, please check if it is working as expected.

**Comment by tonytamps** [comment]
Sorry about the delay. Only just got a chance to test it.
Works great, requires restart to enable the setting which threw me off at first but we got there in the end.

Thanks 👍
