### ISSUE TITLE
Failed to get tab list for <account name>

### ISSUE THREAD

**Issue by vallin91** [briansd9/exile-diary#76]
I've tried setting Exile Diary up but I can't seem to get the app to fetch my tab list. I've entered the correct account name, entered the POESESSID from pathofexile.com while logged in (F12, application, double click on the POESESSID and then copy, and paste it into the app). But I get this message every time "Failed to get tab list for <my account>. Have you entered your account name and POESESSID correctly?". I've also double checked that my profile is not set to private, others can see it, and I am able to import characters into PoB without fault. I am at a loss at what to do to get this to work. Any help is really appreciated!

**Comment by briansd9** [comment]
Is the problem you're encountering similar to this one? Error pops up when you click on the warning in a blank net worth list? https://github.com/briansd9/exile-diary/issues/74

**Comment by vallin91** [comment]
The error was popping up when I tried to look at net worth. But for some reason it's working now that I had left it on while playing PoE yesterday afternoon. Don't know what I did differently other than just leave it active in the background.
