### ISSUE TITLE
Stats and Gear section not loading

### ISSUE THREAD

**Issue by Mayami18** [briansd9/exile-diary#79]
i have an infinite loading screen on my standard character i used to configure and get used to the tool. it worked fine for a while, but then i encountered an alva and it was no longer loading.
here's my log
[log.txt](https://github.com/briansd9/exile-diary/files/5239669/log.txt)

**Comment by briansd9** [comment]
Hi, sorry about that, we'll get this fixed.

Just to confirm, are you seeing the loading image of the 6-socket armour, or is it just a black screen?

I've just uploaded a new release (v0.2.65) with debugging enabled. Can you update to it and then check if there are any errors in the debugging console (the hotkey to open it is Ctrl+Shift+1) when you go to the stats or gear screens?

**Comment by Mayami18** [comment]
i see the loading image, but it doesn't link the sockets anymore, before my alva-map it worked at least for the stats. also tested with a new character in a fresh ssf-league where the gear screen was also working

**Comment by Mayami18** [comment]
just installed the update here is screen of the consoles:
gear: 
![image](https://user-images.githubusercontent.com/71449560/93510160-15035b80-f921-11ea-9271-303fa7cfd508.png)
stats;
![image](https://user-images.githubusercontent.com/71449560/93510284-395f3800-f921-11ea-8f4e-bc991dbd810b.png)
and the log again, if necessary
[log.txt](https://github.com/briansd9/exile-diary/files/5241068/log.txt)

**Comment by briansd9** [comment]
Got it, thanks! Found the bugs, will release a fixed version shortly.

**Comment by briansd9** [comment]
Fixed in v0.2.66, please check.

**Comment by Mayami18** [comment]
everything working now again, awesome. glad to have it all up for Heist later. i wish you a good league start ;)

**Comment by briansd9** [comment]
Cheers, same to you :-)
