### ISSUE TITLE
Net Worth no longer updating

### ISSUE THREAD

**Issue by Mayami18** [briansd9/exile-diary#82]
The Net Worth is no longer updating since yesterday. Tried to change the update-rules between # of map runs and time passed several times. Here is my latest console-data
![image](https://user-images.githubusercontent.com/71449560/93762472-ea125380-fc0f-11ea-9ec3-429a5fec5c24.png)
![image](https://user-images.githubusercontent.com/71449560/93762432-d7981a00-fc0f-11ea-8131-fbb0e4bbfbe9.png)

and my log.txt: 
[log.txt](https://github.com/briansd9/exile-diary/files/5255093/log.txt)

as well as the log.txt from a friend of mine with the same problem. it started around the same time period for him:
[log.txt](https://github.com/briansd9/exile-diary/files/5255098/log.txt)
[log1.txt](https://github.com/briansd9/exile-diary/files/5255099/log1.txt)

**Comment by briansd9** [comment]
Bug found, thanks very much for the detailed report!

Just released v0.2.69 with the fix, please check if it is OK now.

**Comment by Mayami18** [comment]
yeah, networth is updating again. ty for the quick fixing :)
