### ISSUE TITLE
Request feature : Record all characters

### ISSUE THREAD

**Issue by syrm** [briansd9/exile-diary#84]
Hello,

Could you record all characters and and a menu to switch characters and the option to see all characters in « most recent maps »
I switch often character and i need too change settings in app to track the new one each time.

**Comment by briansd9** [comment]
Displaying combined stats from different characters will be very difficult, unfortunately.

It might be possible to automatically change which character is being tracked though... how often do you switch? Do you clear a map with one character and then use a different one to kill the boss, for example?

**Comment by syrm** [comment]
No i change it few times each day

**Comment by syrm** [comment]
In fact i even prefer an account stats for map instead a character one

**Comment by efraimip** [comment]
I agree this is a feature that really limits the usability of this program.
I also switch character often, especially at end game. I have characters designed to do different things.
EG: one fast map clear with MF, one bosser. Often changing on single map. Its actually faster to do both of them by switching (switch takes ~10 sec: drop portal at boss, log out, log in, F2/hideout hotkey, go into portal)

I also do services like boss killing, uberlab, etc. which means I will switch to that character when I get service requests.
exile diary is effectively useless at tracking when switching characters, it just breaks.

**Comment by briansd9** [comment]
Thanks for including the details of how you play, that's valuable info.

One of my goals for this program is to make it usable without any manual actions while you're playing, so I will not implement multiple character tracking unless it can be done automatically... looks like this might be possible.

**Comment by briansd9** [comment]
@syrm Implemented lots of stuff related to this in v0.2.78 (details are in the "About" changelog), let me know what you think.

**Comment by syrm** [comment]
Seems fine, nice work, thank you a lot
