### ISSUE TITLE
Bug : Overlay not on the right screen

### ISSUE THREAD

**Issue by syrm** [briansd9/exile-diary#85]
Hello, 

I have two monitor and i launch POE on the second monitor, Overlay is shown on the first monitor, not on the monitor where POE running.

**Comment by briansd9** [comment]
Will try to fix in next release... don't have a second monitor to test on though.

**Comment by briansd9** [comment]
Added in version 0.2.76, please check if it is working properly now.

**Comment by syrm** [comment]
It’s not fixed sorry

**Comment by syrm** [comment]
Don't bother with that, i'll try to fix it myself and do a PR.
Thank you for your amazing work

**Comment by briansd9** [comment]
Thanks for your help!

I am using [active-win](https://github.com/sindresorhus/active-win/) to position the overlay... seems that multiple monitors are not handled, but I haven't looked too deeply into the source yet
