### ISSUE TITLE
Completely (sortof) not working (sometimes) #2

### ISSUE THREAD

**Issue by efraimip** [briansd9/exile-diary#92]
I read the previous post about "completely not working" and this is similar but seemed to be different from what that guy was experiencing.
https://github.com/briansd9/exile-diary/issues/57

So I have tried installing, uninstalling, wiping data and reinstalling (deleting appdata folder etc), and continually restarting the app etc. So it cant be because of any incorrect installation or startup.

First ---- The behavior I am experiencing is that the program just doesnt track about 50% or more of the maps that I am doing.
I even take screenshot with the map data open on _every_single_map_ just to help it along.
It definitely tracks more maps when I take screenshots, but still doesnt track them all.
I have also tried using sending a whisper to myself "end" like it says in the config as a way to force stop a map run but that has _never_ worked, not once. I dont see it doing anything.
Local chat is on. It DOES track some maps, from time to time....

Secondly --- there are no "kills" count on the majority of my map stats.
I would say 1 in 5 maps will list a kill count. The rest wont.

Third ---- encounters are rarely tracked. I did 3 temples. It tracked one of them. Delving is also not tracked at all. Syndicate same thing.

Fourth ---- if I go to "STATS">"STATS BY AREA" it lists right now 15 maps. If I go to "MAIN" (most recent maps) - it lists 8 maps. Many of the maps it is listing in stats by area are skipped in the "most recent maps" list. Sooooo - it IS tracking some of those maps somewhere? Just not included in my stats or recent map list?

I did about 30 maps yesterday, 2 sirus, and 8 slayers to spawn sirus ofc as well. (8*3 maps to spawn sirus alone wouldve been 24 maps at minimum).
Its tracking 15 of those in stats by area - and 8 of them on most recent map view.

**Comment by briansd9** [comment]
Sorry it's not working as you expect, I'll take a look - can you send me your log file? `%appdata%\exile-diary\log.txt`

**Comment by briansd9** [comment]
Also, requesting screenshot of your "most recent maps" and fully opened "stats by area" tables

**Comment by marketmi** [comment]
> Secondly --- there are no "kills" count on the majority of my map stats.
I would say 1 in 5 maps will list a kill count. The rest wont.

Are you having an incubator active at all times? Otherwise the kill count won't work: https://github.com/briansd9/exile-diary/wiki/(3.7)-Tracking-kill-count-using-incubators

**Comment by efraimip** [comment]
> > Secondly --- there are no "kills" count on the majority of my map stats.
> > I would say 1 in 5 maps will list a kill count. The rest wont.
> 
> Are you having an incubator active at all times? Otherwise the kill count won't work: https://github.com/briansd9/exile-diary/wiki/(3.7)-Tracking-kill-count-using-incubators

yes i do often have incubators on my gear.
are your saying that kill count DOES NOT work while an incubator is active?
that seems counter logical as it would be a valid method to track kills (looking at the incubator between maps)

or are you saying that incubator MUST be active for kill count to work?

**Comment by marketmi** [comment]
> > > Secondly --- there are no "kills" count on the majority of my map stats.
> > > I would say 1 in 5 maps will list a kill count. The rest wont.
> > 
> > 
> > Are you having an incubator active at all times? Otherwise the kill count won't work: https://github.com/briansd9/exile-diary/wiki/(3.7)-Tracking-kill-count-using-incubators
> 
> yes i do often have incubators on my gear.
> are your saying that kill count DOES NOT work while an incubator is active?
> that seems counter logical as it would be a valid method to track kills (looking at the incubator between maps)
> 
> or are you saying that incubator MUST be active for kill count to work?

An incubator must be active for the kill count to work. See the link I provided above.

**Comment by briansd9** [comment]
@efraimip Incubator tracking is as reliable as it gets, so something's clearly not working right - following up on the info I requested above, I'll take a look at this for you.

**Comment by efraimip** [comment]
> @efraimip Incubator tracking is as reliable as it gets, so something's clearly not working right - following up on the info I requested above, I'll take a look at this for you.

Ok this makes sense and it's probably working as intended.
Now that i know i need an incubator to count kills I'll make sure.
So ignore that part at its probably working.
The map tracking though isn't very well.

**Comment by briansd9** [comment]
> The map tracking though isn't very well.

Please send me the following so I can look at this for you:
- Your log file `%appdata%\exile-diary\log.txt`
- Screenshot of your "most recent maps"
- Screenshot of your "stats by area" table with everything opened

**Comment by efraimip** [comment]
Sorry to say but the app is now not tracking ANYTHING at all.
It randomly tracked one zone (in acts, to go raise a spectre) yesterday - and did not track any of the 40+ maps, any delving, any heists I did.......
Same thing today, after the patch, and I did the update all character debug action multiple times, restarted, etc......
Going to have to uninstall, its just not working.

**Comment by briansd9** [comment]
I have requested you to send me your log file twice in this thread already. If you won't, there is nothing I can do to help you.
