### ISSUE TITLE
Wrong map duration in some case

### ISSUE THREAD

**Issue by syrm** [briansd9/exile-diary#93]
Hello,

When you finish a map and leave the game during one week, the map duration will be one week.

You calculate duration like that: 
```
2020/10/24 00:00:00 [INFO Client] : You have entered The Twilight Strand.
2020/10/25 10:00:00 [INFO Client] : You have entered The Old Fields.
```
`The Twilight Strand` duration 34h.

You should calculate it like that:
```
2020/10/24 00:00:00 [INFO Client] : You have entered The Twilight Strand.
2020/10/24 00:15:00 [DEBUG Client] Connect time to instance server was 16ms
2020/10/25 10:00:00 [INFO Client] : You have entered The Old Fields.
```
`The Twilight Strand` duration 15mn.

Or:
```
2020/10/24 00:00:00 [INFO Client] : You have entered The Twilight Strand.
2020/10/24 00:15:00 [INFO Client] : You have entered Celestial Nebula Hideout.
2020/10/25 10:00:00 [INFO Client] : You have entered The Old Fields.
```
`The Twilight Strand` duration 15mn.

You should take the last event meaning you have left the map to calculate the map duration.

**Comment by briansd9** [comment]
As far as I can tell, abnormally long durations only happen when you leave the game while in a map area - logout, Alt-F4, crash, power failure, etc. Is this what happened in your case? 

Make sure to always portal out to avoid this, as a map run only ends on an "Entered [town/hideout]" event (so your first two examples above wouldn't be logged as completed runs yet).

It is annoying to have your stats messed up by this though. Will an option to hide/delete bugged map runs be a good solution for you?

**Comment by syrm** [comment]
Indeed a feature to delete/hide a bugged map is a solution

**Comment by briansd9** [comment]
Added in v0.2.79, please check. Delete button is at the bottom right

**Comment by syrm** [comment]
Perfect, nice work.
Thank you
